apiVersion: v1
kind: Service
metadata:
  name: flogo-rest
  labels:
    app: flogo-rest
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 9999
    name: app
  selector:
    app: flogo-rest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flogo-rest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flogo-rest
    spec:
      containers:
      - name: flogo-rest
        image: ouruser/sinatra:v2
        ports:
        - containerPort: 9999
